apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: strigus
  name: strigus
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
    volumeMounts:
    - name: diretorio-vazio
      mountPath: /strigus
  - image: ubuntu
    name: ubuntu
    args:
    - sleep
    - "600"
    resources:
      limits:
        cpu: "1"
        memory: "256Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
    volumeMounts:
    - name: diretorio-vazio
      mountPath: /strigus
  - image: busybox
    name: busybox
    args:
    - sleep
    - "500"
    resources:
      limits:
        cpu: "0.5"
      requests:
        cpu: "0.1"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: diretorio-vazio
    emptyDir:
      sizeLimit: 256Mi
status: {}
