apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    resources:
      limits: # Limite máximo do container
        memory: "128Mi"
        cpu: "0.5"
      requests: # Garante os limites (minimo?) do container 
        memory: "64Mi"
        cpu: "0.3"
    args:
    - sleep
    - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
